/*
  Auto-generated by Spline
  Note: This uses @splinetool/r3f-spline which has compatibility issues with Three.js 0.182+
  Currently using the standalone @splinetool/react-spline component in HeroModern.tsx instead
*/

import useSpline from '@splinetool/r3f-spline'
import { OrthographicCamera } from '@react-three/drei'

export default function SplineScene({ ...props }) {
  const { nodes, materials } = useSpline('https://prod.spline.design/inTyBAsCyiY4aWGe/scene.splinecode')
  return (
    <>
      <color attach="background" args={['#1e293b']} />
      <group {...props} dispose={null}>
        <scene name="Scene 1">
          <OrthographicCamera
            name="Camera"
            makeDefault={true}
            zoom={1.67}
            far={100000}
            near={-100000}
            up={[0, 1, 0]}
            position={[1653.58, 1834.46, 1559.88]}
            rotation={[-0.71, 0.66, 0.49]}
            scale={[1, 1.06, 1]}
          />
          <directionalLight
            name="Directional Light"
            castShadow
            intensity={0.7}
            shadow-mapSize-width={1024}
            shadow-mapSize-height={1024}
            shadow-camera-near={-10000}
            shadow-camera-far={100000}
            shadow-camera-left={-1000}
            shadow-camera-right={1000}
            shadow-camera-top={1000}
            shadow-camera-bottom={-1000}
            position={[-1250.56, 1135.38, 526.46]}
          />
          <group
            name="Rectangle 2 Clones"
            position={[566.65, -142, -81.45]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[-0.25, 0.25, 0.25]}
          >
            <group name="Clone 0" position={[0, 0, -1572]}>
              <mesh
                name="0b"
                geometry={nodes['0b'].geometry}
                material={materials['Light Blu']}
                castShadow
                receiveShadow
                position={[0, 0, -365.6]}
                rotation={[0, 0, 0]}
              />
            </group>
            <group name="Clone 1" position={[320, 0, -1692]}>
              <mesh
                name="1b"
                geometry={nodes['1b'].geometry}
                material={materials.Blue}
                castShadow
                receiveShadow
                position={[0, 0, -724.43]}
                rotation={[0, 0, 0]}
              />
            </group>
            <group name="Clone 2b" position={[640, 0, -1838]}>
              <mesh
                name="2b"
                geometry={nodes['2b'].geometry}
                material={materials['Dark Blue']}
                castShadow
                receiveShadow
                position={[0, 0, -1073.11]}
                rotation={[0, 0, 0]}
              />
            </group>
            <group name="Clone 3" position={[960, 0, -1967]}>
              <mesh
                name="3b"
                geometry={nodes['3b'].geometry}
                material={materials['Dark Blu Noise']}
                castShadow
                receiveShadow
                position={[0, 0, -1428.55]}
                rotation={[0, 0, 0]}
              />
            </group>
          </group>
          <group name="Rectangle Clones" position={[0, -238, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.25}>
            <group name="Clone 01" position={[0, 0, -2030]}>
              <mesh
                name="0"
                geometry={nodes['0'].geometry}
                material={materials['Light Blu']}
                castShadow
                receiveShadow
                position={[0, 0, 0]}
                rotation={[0, 0, 0]}
              />
            </group>
            <group name="Clone 11" position={[320, 0, -1873.54]} scale={1}>
              <mesh
                name="1"
                geometry={nodes['1'].geometry}
                material={materials.Blue}
                castShadow
                receiveShadow
                position={[0, 0, -345.29]}
                rotation={[0, 0, 0]}
              />
            </group>
            <group name="Clone 2" position={[640, 0, -1738.1]} scale={1}>
              <mesh
                name="2"
                geometry={nodes['2'].geometry}
                material={materials['Dark Blue']}
                castShadow
                receiveShadow
                position={[0, 0, -695.26]}
                rotation={[0, 0, 0]}
              />
            </group>
            <group name="Clone 31" position={[960, 0, -1594.15]} scale={1}>
              <mesh
                name="3"
                geometry={nodes['3'].geometry}
                material={materials['Blue noise']}
                castShadow
                receiveShadow
                position={[0, 0, -1035.87]}
                rotation={[0, 0, 0]}
              />
            </group>
          </group>
          <OrthographicCamera name="4" makeDefault={false} far={10000} near={-50000} />
          <hemisphereLight name="Default Ambient Light" intensity={0.75} color="#eaeaea" />
        </scene>
      </group>
    </>
  )
}
